language: objective-c

project: ChordDetector.xcodeproj
scheme: ChordDetector
test_scheme: ChordDetectorTests
osx_image: xcode11
xcode_sdk: macosx10.15

script:
  - xcodebuild -workspace ChordDetector.xcworkspace -scheme ChordDetector ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
  - xcodebuild -workspace ChordDetector.xcworkspace -scheme ChordDetectorTests test ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
