language: objective-c

workspace: ChordDetector.xcworkspace
scheme: ChordDetector
test_scheme: ChordDetectorTests
osx_image: xcode10
xcode_sdk: macosx10.14

before_install:
  - gem install cocoapods
  - pod repo update

script:
  - xcodebuild -workspace ChordDetector.xcworkspace -scheme ChordDetector ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
  - xcodebuild -workspace ChordDetector.xcworkspace -scheme ChordDetectorTests test ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
