language: objective-c

workspace: ChordDetector.xcworkspace
scheme: ChordDetector
test_scheme: ChordDetectorTests
osx_image: xcode10
xcode_sdk: macosx10.14

before_install:
  - gem install cocoapods
  - pod repo update

script:
  - pod install
  - xcodebuild -workspace ChordDetector.xcworkspace -scheme ChordDetector ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
  - xcodebuild test -workspace ChordDetector.xcworkspace -scheme ChordDetectorTests ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
