language: objective-c

workspace: ChordDetector.xcworkspace
scheme: ChordDetector
test_scheme: ChordDetectorTests
osx_image: xcode8.3
xcode_sdk: macosx10.12

script:
  - pod install
  - xcodebuild -workspace ChordDetector.xcworkspace -scheme ChordDetector ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

  - xcodebuild test -workspace ChordDetector.xcworkspace -scheme ChordDetectorTests ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
